/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.h
**     Project     : S32K118F256
**     Processor   : S32K118_64
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-06-19, 09:54, # CodeGen: 0
**     Abstract    :
**
**     Settings    :
**          Component name                                 : pin_mux
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : S32K118_64
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC0
**                ADC0                                     : 
**                  ADC Channel 0                          : <Automatic>
**                  ADC Channel 1                          : <Automatic>
**                  ADC Channel 2                          : <Automatic>
**                  ADC Channel 3                          : <Automatic>
**                  ADC Channel 4                          : <Automatic>
**                  ADC Channel 5                          : <Automatic>
**                  ADC Channel 6                          : <Automatic>
**                  ADC Channel 7                          : <Automatic>
**                  ADC Channel 8                          : <Automatic>
**                  ADC Channel 9                          : <Automatic>
**                  ADC Channel 10                         : <Automatic>
**                  ADC Channel 11                         : <Automatic>
**                  ADC Channel 12                         : <Automatic>
**                  ADC Channel 13                         : <Automatic>
**                  ADC Channel 14                         : <Automatic>
**                  ADC Channel 15                         : <Automatic>
**              Peripheral Type AIPS                       : 
**                Custom name                              : AIPS
**              Peripheral Type CAN                        : 
**                Custom name                              : CAN0
**                CAN0                                     : 
**                  CAN Receiver Input                     : <Automatic>
**                  CAN Transmitter Output                 : <Automatic>
**              Peripheral Type CMP                        : 
**                Custom name                              : CMP0
**                CMP0                                     : 
**                  CMP Comparator Input 0                 : <Automatic>
**                  CMP Comparator Input 1                 : <Automatic>
**                  CMP Comparator Input 2                 : <Automatic>
**                  CMP Comparator Input 3                 : <Automatic>
**                  CMP Comparator Input 4                 : <Automatic>
**                  CMP Comparator Input 5                 : <Automatic>
**                  CMP Comparator Input 6                 : <Automatic>
**                  CMP Comparator Input 7                 : <Automatic>
**                  CMP Comparator Output                  : <Automatic>
**                  CMP Round Robin Port Output Trigger    : <Automatic>
**              Peripheral Type CMU_FC                     : 
**                Custom name                              : CMU_FC_0
**                Custom name                              : CMU_FC_1
**              Peripheral Type CRC                        : 
**                Custom name                              : CRC
**              Peripheral Type CSE_PRAM                   : 
**                Custom name                              : CSE_PRAM
**              Peripheral Type DMA                        : 
**                Custom name                              : DMA
**              Peripheral Type DMAMUX                     : 
**                Custom name                              : DMAMUX
**              Peripheral Type EIM                        : 
**                Custom name                              : EIM
**              Peripheral Type ERM                        : 
**                Custom name                              : ERM
**              Peripheral Type FLEXIO                     : 
**                Custom name                              : FLEXIO
**                FLEXIO                                   : 
**                  Data Pin 0                             : <Automatic>
**                  Data Pin 1                             : <Automatic>
**                  Data Pin 2                             : <Automatic>
**                  Data Pin 3                             : <Automatic>
**                  Data Pin 4                             : <Automatic>
**                  Data Pin 5                             : <Automatic>
**                  Data Pin 6                             : <Automatic>
**                  Data Pin 7                             : <Automatic>
**              Peripheral Type FTFC                       : 
**                Custom name                              : FTFC
**              Peripheral Type FTM                        : 
**                Custom name                              : FTM0
**                FTM0                                     : 
**                  FTM Channel 0                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 1                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 2                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 3                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 4                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 5                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 6                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 7                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Fault Input 0                      : <Automatic>
**                  FTM Fault Input 1                      : <Automatic>
**                  FTM Fault Input 2                      : <Automatic>
**                  FTM Fault Input 3                      : <Automatic>
**                  FTM Common External Clock Input 0      : <Automatic>
**                  FTM Common External Clock Input 1      : <Automatic>
**                  FTM Common External Clock Input 2      : <Automatic>
**                Custom name                              : FTM1
**                FTM1                                     : 
**                  FTM Channel 0                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 1                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 2                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 3                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 4                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 5                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 6                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Channel 7                          : <Automatic>
**                  Direction                              : <Automatic>
**                  FTM Fault Input 0                      : <Automatic>
**                  FTM Fault Input 1                      : <Automatic>
**                  FTM Fault Input 2                      : <Automatic>
**                  FTM Fault Input 3                      : <Automatic>
**                  FTM Quadrature Decoder Phase A         : <Automatic>
**                  FTM Quadrature Decoder Phase B         : <Automatic>
**              Peripheral Type GPIO                       : 
**                Custom name                              : PTA
**                PTA                                      : 
**                  Pin GPIO0                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO1                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO2                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO3                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO4(JTAG)                        : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO5                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO6                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO7                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO10(JTAG)                       : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO11                             : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO12                             : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO13                             : <Automatic>
**                  Direction                              : <Automatic>
**                Custom name                              : PTB
**                PTB                                      : 
**                  Pin GPIO0                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO1                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO2                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO3                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO4                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO5                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO6                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO7                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO12                             : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO13                             : <Automatic>
**                  Direction                              : <Automatic>
**                Custom name                              : PTC
**                PTC                                      : 
**                  Pin GPIO0                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO1                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO2                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO3                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO4(JTAG)                        : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO5(JTAG)                        : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO6                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO7                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO8                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO9                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO14                             : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO15                             : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO16                             : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO17                             : <Automatic>
**                  Direction                              : <Automatic>
**                Custom name                              : PTD
**                PTD                                      : 
**                  Pin GPIO0                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO1                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO2                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO3                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO4                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO5                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO6                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO7                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO15                             : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO16                             : <Automatic>
**                  Direction                              : <Automatic>
**                Custom name                              : PTE
**                PTE                                      : 
**                  Pin GPIO0                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO1                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO2                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO3                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO4                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO5                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO6                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO7                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO8                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO9                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO10                             : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin GPIO11                             : <Automatic>
**                  Direction                              : <Automatic>
**              Peripheral Type JTAG                       : 
**                JTAG                                     : 
**                  Test Clock                             : <Automatic>
**                  Test Data Input                        : <Automatic>
**                  Test Data Output                       : <Automatic>
**                  Test Mode Selection                    : <Automatic>
**              Peripheral Type LMEM                       : 
**                Custom name                              : LMEM
**              Peripheral Type LPI2C                      : 
**                Custom name                              : LPI2C0
**                LPI2C0                                   : 
**                  I2C Host Request Input                 : <Automatic>
**                  I2C Serial Clock Line                  : <Automatic>
**                  I2C Secondary Clock line               : <Automatic>
**                  I2C Serial Data Line                   : <Automatic>
**                  I2C Secondary Data Line                : <Automatic>
**              Peripheral Type LPIT                       : 
**                Custom name                              : LPIT0
**              Peripheral Type LPSPI                      : 
**                Custom name                              : LPSPI0
**                LPSPI0                                   : 
**                  LPSPI Peripheral Chip Select 0         : <Automatic>
**                  Direction                              : <Automatic>
**                  LPSPI Peripheral Chip Select 1         : <Automatic>
**                  Direction                              : <Automatic>
**                  LPSPI Peripheral Chip Select 2         : <Automatic>
**                  Direction                              : <Automatic>
**                  LPSPI Serial Clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  LPSPI Serial Data Input                : <Automatic>
**                  Direction                              : <Automatic>
**                  LPSPI Serial Data Output               : <Automatic>
**                  Direction                              : <Automatic>
**                Custom name                              : LPSPI1
**                LPSPI1                                   : 
**                  LPSPI Peripheral Chip Select 0         : <Automatic>
**                  Direction                              : <Automatic>
**                  LPSPI Peripheral Chip Select 1         : <Automatic>
**                  Direction                              : <Automatic>
**                  LPSPI Serial Clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  LPSPI Serial Data Input                : <Automatic>
**                  Direction                              : <Automatic>
**                  LPSPI Serial Data Output               : <Automatic>
**                  Direction                              : <Automatic>
**              Peripheral Type LPTMR                      : 
**                Custom name                              : LPTMR0
**                LPTMR0                                   : 
**                  LPTMR Pulse counter input 1            : <Automatic>
**                  LPTMR Pulse counter input 2            : <Automatic>
**                  LPTMR Pulse counter input 3            : <Automatic>
**              Peripheral Type LPUART                     : 
**                Custom name                              : LPUART0
**                LPUART0                                  : 
**                  LPUART Clear to Send                   : <Automatic>
**                  LPUART Request to Send                 : <Automatic>
**                  LPUART Receive Data                    : <Automatic>
**                  LPUART Transmit Data                   : <Automatic>
**                  Direction                              : <Automatic>
**                Custom name                              : LPUART1
**                LPUART1                                  : 
**                  LPUART Clear to Send                   : <Automatic>
**                  LPUART Request to Send                 : <Automatic>
**                  LPUART Receive Data                    : <Automatic>
**                  LPUART Transmit Data                   : <Automatic>
**                  Direction                              : <Automatic>
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type MPU                        : 
**                Custom name                              : MPU
**              Peripheral Type MSCM                       : 
**                Custom name                              : MSCM
**              Peripheral Type OSC                        : 
**              Peripheral Type PCC                        : 
**                Custom name                              : PCC
**              Peripheral Type PDB                        : 
**                Custom name                              : PDB0
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**              Peripheral Type PORT                       : 
**                Custom name                              : PORTA
**                Custom name                              : PORTB
**                Custom name                              : PORTC
**                Custom name                              : PORTD
**                Custom name                              : PORTE
**              Peripheral Type Platform                   : 
**                Platform                                 : 
**                  Clock Output                           : <Automatic>
**                  Clock Output                           : <Automatic>
**                  Non-Maskable Interrupt                 : <Automatic>
**                  Reset                                  : <Automatic>
**              Peripheral Type PowerAndGround             : 
**                PowerAndGround                           : 
**                  Supply Voltage                         : VDD7
**                  Supply Voltage                         : VDD41
**                  Analogue Supply Voltage                : VDDA
**                  ADC Reference Supply High              : VREFH
**                  Supply Ground                          : VSS10
**                  Supply Ground                          : VSS40
**              Peripheral Type RCM                        : 
**                Custom name                              : RCM
**              Peripheral Type RTC                        : 
**                Custom name                              : RTC
**                RTC                                      : 
**                  RTC Clock Input                        : <Automatic>
**                  RTC Clock Output                       : <Automatic>
**              Peripheral Type S32_NVIC                   : 
**              Peripheral Type S32_SCB                    : 
**                Custom name                              : S32_SCB
**              Peripheral Type S32_SysTick                : 
**                Custom name                              : S32_SysTick
**              Peripheral Type SCG                        : 
**                Custom name                              : SCG
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**              Peripheral Type SMC                        : 
**                Custom name                              : SMC
**              Peripheral Type SWD                        : 
**                SWD                                      : 
**                  Clock                                  : <Automatic>
**                  Data Input/Output                      : <Automatic>
**              Peripheral Type TRGMUX                     : 
**                Custom name                              : TRGMUX
**                TRGMUX                                   : 
**                  TRGMUX Input 0                         : <Automatic>
**                  TRGMUX Input 1                         : <Automatic>
**                  TRGMUX Input 2                         : <Automatic>
**                  TRGMUX Input 3                         : <Automatic>
**                  TRGMUX Input 4                         : <Automatic>
**                  TRGMUX Input 5                         : <Automatic>
**                  TRGMUX Input 6                         : <Automatic>
**                  TRGMUX Input 7                         : <Automatic>
**                  TRGMUX Input 8                         : <Automatic>
**                  TRGMUX Input 9                         : <Automatic>
**                  TRGMUX Output 0                        : <Automatic>
**                  TRGMUX Output 1                        : <Automatic>
**                  TRGMUX Output 2                        : <Automatic>
**                  TRGMUX Output 3                        : <Automatic>
**                  TRGMUX Output 4                        : <Automatic>
**                  TRGMUX Output 5                        : <Automatic>
**              Peripheral Type WDOG                       : 
**                Custom name                              : WDOG
**              Non-peripheral pins                        : 
**            Electrical properties                        : 
**              Pin 1: PTD1                                : 
**                Custom name, Signal name                 : PTD1
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 2: PTD0                                : 
**                Custom name, Signal name                 : PTD0
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 3: PTE11                               : 
**                Custom name, Signal name                 : PTE11
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 4: PTE10                               : 
**                Custom name, Signal name                 : PTE10
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 5: PTE5                                : 
**                Custom name, Signal name                 : PTE5
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 6: PTE4                                : 
**                Custom name, Signal name                 : PTE4
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 7: VDD7                                : 
**                Custom name, Signal name                 : VDD7
**              Pin 8: VDDA                                : 
**                Custom name, Signal name                 : VDDA
**              Pin 9: VREFH                               : 
**                Custom name, Signal name                 : VREFH
**              Pin 10: VSS10                              : 
**                Custom name, Signal name                 : VSS10
**              Pin 11: PTB7                               : 
**                Custom name, Signal name                 : PTB7
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 12: PTB6                               : 
**                Custom name, Signal name                 : PTB6
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 13: PTE3                               : 
**                Custom name, Signal name                 : PTE3
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 14: PTD16                              : 
**                Custom name, Signal name                 : PTD16
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 15: PTD15                              : 
**                Custom name, Signal name                 : PTD15
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 16: PTE9                               : 
**                Custom name, Signal name                 : PTE9
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 17: PTE8                               : 
**                Custom name, Signal name                 : PTE8
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 18: PTB5                               : 
**                Custom name, Signal name                 : PTB5
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 19: PTB4                               : 
**                Custom name, Signal name                 : PTB4
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 20: PTC3                               : 
**                Custom name, Signal name                 : PTC3
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 21: PTC2                               : 
**                Custom name, Signal name                 : PTC2
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 22: PTD7                               : 
**                Custom name, Signal name                 : PTD7
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 23: PTD6                               : 
**                Custom name, Signal name                 : PTD6
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 24: PTD5                               : 
**                Custom name, Signal name                 : PTD5
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 25: PTC1                               : 
**                Custom name, Signal name                 : PTC1
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 26: PTC0                               : 
**                Custom name, Signal name                 : PTC0
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 27: PTC17                              : 
**                Custom name, Signal name                 : PTC17
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 28: PTC16                              : 
**                Custom name, Signal name                 : PTC16
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 29: PTC15                              : 
**                Custom name, Signal name                 : PTC15
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 30: PTC14                              : 
**                Custom name, Signal name                 : PTC14
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 31: PTB3                               : 
**                Custom name, Signal name                 : PTB3
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 32: PTB2                               : 
**                Custom name, Signal name                 : PTB2
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 33: PTB1                               : 
**                Custom name, Signal name                 : PTB1
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 34: PTB0                               : 
**                Custom name, Signal name                 : PTB0
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 35: PTC9                               : 
**                Custom name, Signal name                 : PTC9
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 36: PTC8                               : 
**                Custom name, Signal name                 : PTC8
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 37: PTA7                               : 
**                Custom name, Signal name                 : PTA7
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 38: PTA6                               : 
**                Custom name, Signal name                 : PTA6
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 39: PTE7                               : 
**                Custom name, Signal name                 : PTE7
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 40: VSS40                              : 
**                Custom name, Signal name                 : VSS40
**              Pin 41: VDD41                              : 
**                Custom name, Signal name                 : VDD41
**              Pin 42: PTB13                              : 
**                Custom name, Signal name                 : PTB13
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 43: PTB12                              : 
**                Custom name, Signal name                 : PTB12
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 44: PTD4                               : 
**                Custom name, Signal name                 : PTD4
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 45: PTD3                               : 
**                Custom name, Signal name                 : PTD3
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Passive Filter Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 46: PTD2                               : 
**                Custom name, Signal name                 : PTD2
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 47: PTA3                               : 
**                Custom name, Signal name                 : PTA3
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 48: PTA2                               : 
**                Custom name, Signal name                 : PTA2
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 49: PTA1                               : 
**                Custom name, Signal name                 : PTA1
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 50: PTA0                               : 
**                Custom name, Signal name                 : PTA0
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 51: PTC7                               : 
**                Custom name, Signal name                 : PTC7
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 52: PTC6                               : 
**                Custom name, Signal name                 : PTC6
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 53: PTE6                               : 
**                Custom name, Signal name                 : PTE6
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 54: PTE2                               : 
**                Custom name, Signal name                 : PTE2
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 55: PTA13                              : 
**                Custom name, Signal name                 : PTA13
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 56: PTA12                              : 
**                Custom name, Signal name                 : PTA12
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 57: PTA11                              : 
**                Custom name, Signal name                 : PTA11
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 58: PTA10                              : 
**                Custom name, Signal name                 : PTA10
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 59: PTE1                               : 
**                Custom name, Signal name                 : PTE1
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 60: PTE0                               : 
**                Custom name, Signal name                 : PTE0
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Drive Strength Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 61: PTC5                               : 
**                Custom name, Signal name                 : PTC5
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 62: PTC4                               : 
**                Custom name, Signal name                 : PTC4
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 63: PTA5                               : 
**                Custom name, Signal name                 : PTA5
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Passive Filter Field                     : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**              Pin 64: PTA4                               : 
**                Custom name, Signal name                 : PTA4
**                Interrupt Status Field                   : <Automatic>
**                Interrupt Configuration Field            : <Automatic>
**                Pin Mux Field                            : <Automatic>
**                Lock Field                               : <Automatic>
**                Pull Enable Field                        : <Automatic>
**                Pull Select Field                        : <Automatic>
**                Initial Value Field                      : <Automatic>
**                Digital Filter Field                     : <Automatic>
**          Settings                                       : 
**            PinSetting Configuration Generation Settings : 
**              UtilizeResetValuesCondGroup                : Only if property present
**                Generate configured Pins only            : yes
**              Shared components                          : 
**                clock_manager                            : clockMan1
**     Contents    :
**         PINS_DRV_Init                 - status_t PINS_DRV_Init(uint32_t pinCount,const pin_settings_config_t config[]);
**         PINS_DRV_SetPullSel           - void PINS_DRV_SetPullSel(PORT_Type * const base,uint32_t...
**         PINS_DRV_SetMuxModeSel        - void PINS_DRV_SetMuxModeSel(PORT_Type * const base,uint32_t pin,port_mux_t mux);
**         PINS_DRV_SetPinIntSel         - void PINS_DRV_SetPinIntSel(PORT_Type * const base,uint32_t...
**         PINS_DRV_GetPinIntSel         - port_interrupt_config_t PINS_DRV_GetPinIntSel(const PORT_Type * const...
**         PINS_DRV_ClearPinIntFlagCmd   - void PINS_DRV_ClearPinIntFlagCmd(PORT_Type * const base,uint32_t pin);
**         PINS_DRV_EnableDigitalFilter  - void PINS_DRV_EnableDigitalFilter(PORT_Type * const base,uint32_t pin);
**         PINS_DRV_DisableDigitalFilter - void PINS_DRV_DisableDigitalFilter(PORT_Type * const base,uint32_t pin);
**         PINS_DRV_ConfigDigitalFilter  - void PINS_DRV_ConfigDigitalFilter(PORT_Type * const base,const...
**         PINS_DRV_GetPortIntFlag       - uint32_t PINS_DRV_GetPortIntFlag(const PORT_Type * const base);
**         PINS_DRV_ClearPortIntFlagCmd  - void PINS_DRV_ClearPortIntFlagCmd(PORT_Type * const base);
**         PINS_DRV_SetGlobalPinControl  - void PINS_DRV_SetGlobalPinControl(PORT_Type * const base, uint16_t pins,...
**         PINS_DRV_SetGlobalIntControl  - void PINS_DRV_SetGlobalIntControl(PORT_Type * const base, uint16_t pins,...
**         PINS_DRV_GetPinsDirection     - pins_channel_type_t PINS_DRV_GetPinsDirection(const GPIO_Type * const base);
**         PINS_DRV_SetPinDirection      - void PINS_DRV_SetPinDirection(GPIO_Type * const base,pins_channel_type_t...
**         PINS_DRV_SetPinsDirection     - void PINS_DRV_SetPinsDirection(GPIO_Type * const base,pins_channel_type_t pins);
**         PINS_DRV_WritePin             - void PINS_DRV_WritePin(GPIO_Type * const base,pins_channel_type_t...
**         PINS_DRV_WritePins            - void PINS_DRV_WritePins(GPIO_Type * const base,pins_channel_type_t pins);
**         PINS_DRV_GetPinsOutput        - pins_channel_type_t PINS_DRV_GetPinsOutput(const GPIO_Type * const base);
**         PINS_DRV_SetPins              - void PINS_DRV_SetPins(GPIO_Type * const base,pins_channel_type_t pins);
**         PINS_DRV_ClearPins            - void PINS_DRV_ClearPins(GPIO_Type * const base,pins_channel_type_t pins);
**         PINS_DRV_TogglePins           - void PINS_DRV_TogglePins(GPIO_Type * const base,pins_channel_type_t pins);
**         PINS_DRV_ReadPins             - pins_channel_type_t PINS_DRV_ReadPins(const GPIO_Type * const base);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file pin_mux.h
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

#ifndef pin_mux_H
#define pin_mux_H

/* MODULE pin_mux. */
#include "pins_driver.h"


/*! @brief No pin was configured different with reset value */

/* END pin_mux. */
#endif /* #ifndef pin_mux_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
